### ISSUE TITLE
frameviz.js and the SEMAFOR v3 JSON structure

### ISSUE THREAD

**Issue by alhuber1502** [sammthomson/semviz#2]
There appears to be a problem with a couple of small changes in the JSON structure that is created by SEMAFOR v2.1 vs. v3.0.4-alph.

The first one involves a change in the "target" section:

v2.1:
     "target": {
        "start": 0,
        "end": 1,
        "name": "Relational_quantity",
        "text": "Exhausted"
      }

v3.0.4-alpha:
     "target": {
        "name": "Used_up",
        "spans": [
                {
                "start": 0,
                "end": 1,
                "text": "Exhausted"
                }
        ],
        "type": "target"
      }

The second change is in the "annotationSets":

v2.1:
      "annotationSets": [
        {
          "frameElements": [
            {
              "start": 0,
              "end": 1,
              "name": "Denoted_quantity",
              "text": "Exhausted"
            }
          ],
          "score": 15.141333174135688,
          "rank": 0
        }
      ]

v3.0.4-alpha:
        "annotationSets": [
                {
                "rank": 0,
                "score": 15.646716850622685,
                "frameElements": [
                    {
                        "name": "Resource",
                        "spans": [
                                {
                                "start": 1,
                                "end": 3,
                                "text": "themes !"
                                }
                        ]
                    },
                    {
                        "name": "Used_up",
                        "spans": [
                                {
                                "start": 0,
                                "end": 1,
                                "text": "Exhausted"
                        }
                        ],
                        "type": "target"
                    }
                ]
                }
        ]

**Comment by nschneid** [comment]
Looks like the solution will involve adding some additional for loops below https://github.com/sammthomson/semviz/blob/master/semviz/static/js/frameviz.js#L178 – hopefully this can be a backward-compatible change. @sammthomson, is the new JSON format stabilized?

**Comment by sammthomson** [comment]
Probably, yeah. No immediate plans to change it.

**Comment by nschneid** [comment]
OK, I've modified frameviz with what should work at least as a Band-Aid. Doesn't actually handle the case of discontinuous targets or FEs, but I don't know if SEMAFOR outputs those anyway.

@sammthomson, could you give me push permissions to the repository?

**Comment by nschneid** [comment]
Title text has "undefined" for the span value

**Comment by sammthomson** [comment]
Thanks Nathan. And thanks for the report Alexander
